### ISSUE TITLE
UI menu auto hide not enable

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#10]
Area Path: USERS menu > New Users
Build Number: Version Number 1.0.0 (504)
Severity: medium 
Priority: medium

Environment: iOS 
Description:
open app> start> menu does not auto hide after a few seconds

Steps To Reproduce:
1) Logon into the application
2) press start

Expected result: menu auto hide after a few seconds

**Comment by fishkingsin** [comment]
fixed with 504
