### ISSUE TITLE
UI color gradient not right

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#11]
Build Number: Version Number 1.0.0 (504)
Severity: HIGH 
Priority: HIGH

Environment: iOS 
Description:
the color gradient display for "balls" and gradient menu is different from the one sent in ai file

Steps To Reproduce:
1) Logon into the application
2) press start

Expected result: right blue gradient as provided in Archipelodio_UIDesign_2604.ai

**Comment by fishkingsin** [comment]
fixed with 504
