### ISSUE TITLE
UI design problems vers 2.0 (2)

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#13]
![img_2606](https://cloud.githubusercontent.com/assets/18543485/15139203/44157458-16c7-11e6-9b26-7fdce16bd698.PNG)
blue dotted lines and dotted circles are too thick, and the whole space is not entered on screen.

**Comment by fishkingsin** [comment]
please show your expected screen

**Comment by fishkingsin** [comment]
@cedricmrdt 
<img width="2032" alt="screen shot 2016-05-10 at 4 33 22 pm" src="https://cloud.githubusercontent.com/assets/481343/15140310/1195ac40-16cd-11e6-8de0-3364b5206466.png">

please check

**Comment by fishkingsin** [comment]
fixed with 2.0 (4)
