### ISSUE TITLE
ui design problem vers 2.0 (2) balls

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#18]
blue balls:
- color gradient seems not like the one I sent you 
  gradient should be from  R= 99    G= 228   B= 255  (close)  to R=109 G=255 B=191(far) 
- closer balls from listener should be smaller / further away from listener bigger

expected: make the one closer to lister smaller, and keep same size as current for far away.

**Comment by fishkingsin** [comment]
@cedricmrdt 
R=109 G=255 B=191?
<img width="763" alt="screen shot 2016-05-10 at 10 57 19 pm" src="https://cloud.githubusercontent.com/assets/481343/15151159/a086a5fa-1702-11e6-84a8-dc37e81a55b0.png">

**Comment by fishkingsin** [comment]
please use tool http://www.workwithcolor.com/color-converter-01.htm

**Comment by cedricmrdt** [comment]
It the gradient from the ai i sent you.

I misinterpret the code today

gradient from 

to
