### ISSUE TITLE
ui design problem vers 2.0 (4)

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#20]
the menu is not covering the dotted line and they mix

expected: when the menu is on, it should have a white background so it covers the dotted lines.

![img_2609](https://cloud.githubusercontent.com/assets/18543485/15172151/891007fc-1786-11e6-949d-f232aac20a6e.PNG)

**Comment by fishkingsin** [comment]
fixed with 2.1
