### ISSUE TITLE
typo version 2.1 (1)

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#21]
![img_2650](https://cloud.githubusercontent.com/assets/18543485/15274037/1bab382c-1adc-11e6-981f-2734891568f5.PNG)

text should be "downloading error occurred, please retry" "retry"

**Comment by fishkingsin** [comment]
@cedricmrdt 
<img width="593" alt="screen shot 2016-05-15 at 9 28 52 pm" src="https://cloud.githubusercontent.com/assets/481343/15274439/0fa0d48a-1ae4-11e6-8bc2-0074213a23f1.png">

**Comment by cedricmrdt** [comment]
just put "downloading error occurred"

then button retry
thanks

**Comment by fishkingsin** [comment]
@cedricmrdt 
<img width="590" alt="screen shot 2016-05-15 at 9 39 34 pm" src="https://cloud.githubusercontent.com/assets/481343/15274492/8e24e6ba-1ae5-11e6-9e85-956892433989.png">

**Comment by cedricmrdt** [comment]
ok! thanks
