### ISSUE TITLE
number of user does't refresh version 2.1 (1)

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#24]
load and start the application, go to http://www.moneme.com/Archipelodio/api/usertest?numuser=11 and change the number os users, no refresh on screen of new users amount, even when waiting long time. no change in the sound stream number (it seems)

the number of users should be reflected on screen visually and aurally.

**Comment by fishkingsin** [comment]
use
 http://www.mb09.com/ARCHIPELAUDIO/api/usertest?numuser=20 
instead
