### ISSUE TITLE
UI resolution

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#5]
the general feel of resolution of the app seems low. like the cycles of listeners are very pixelated. lines are not so thin and pixelated.

**Comment by fishkingsin** [comment]
@cedricmrdt 
please screen cap and point out the issue you have found , it is not clear by text  description

**Comment by cedricmrdt** [comment]
All the red dots doesn’t look sharp on my device, especially the dashed lines and the balls that are not round.
