### ISSUE TITLE
UI design problems

### ISSUE THREAD

**Issue by cedricmrdt** [fishkingsin/Archipelodio#9]
Area Path: USERS menu > New Users
Build Number: Version Number 1.0.0 (450)
Severity: HIGH 
Priority: HIGH 

Environment: iOS 
Description:
- blue rectangle on the screen of 3d space once opened
- colour gradient of the user's ball is not the one sent in ai file.

Steps To Reproduce:
1) Logon into the application
2) press start
3) add users

---

Expected result: no blue block, and right colours as sent.

**Comment by cedricmrdt** [comment]
![img_2500](https://cloud.githubusercontent.com/assets/18543485/14805627/24eb758c-0ba0-11e6-89d9-fb2a4795a60d.PNG)
![img_2499](https://cloud.githubusercontent.com/assets/18543485/14805631/2fe72bca-0ba0-11e6-9c93-7cd78fb11f01.PNG)

**Comment by cedricmrdt** [comment]
Same issue with 457 build

**Comment by fishkingsin** [comment]
fixed with 1.0.0(502)
